name: Build and Deploy Franklin Site
on:
  push:
    branches:
      - main  # Remove "master" unless you actively use it

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write  # Allows pushing to `gh-pages`
    steps:
    - name: Checkout Code
      uses: actions/checkout@v4

    - name: Install Julia
      uses: julia-actions/setup-julia@v1
      with:
        version: '1.9'  # Match your local Julia version (safer than '1')

    - name: Install Dependencies
      run: |
        julia --project -e '
          using Pkg;
          Pkg.activate(".");
          Pkg.instantiate();
          Pkg.add("Franklin");
          Pkg.add("NodeJS");
          using NodeJS;
          run(`$(npm_cmd()) install highlight.js`);
        '

    - name: Build Site
      run: |
        julia --project -e '
          using Franklin;
          optimize()'  # Enable minify/prerender unless you have issues

    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3  # Better than JamesIves for Franklin
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./__site  # Franklin’s output folder
        keep_files: false      # Clean old files on deploy
